{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosca-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /mosca
        pathType: Prefix
        backend:
          service:
            name: mosca-mosquitto
            port:
              number: 1883
{{- end }}
